[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zstar"
version = "0.1.0"
description = "Zstar: A code for calculations of Born effective charge and dielectric responses."
readme = "README_PYPI.md"
requires-python = ">=3.9"
license = "GPL-3.0-only"

authors = [
  { name = "Xudong Zhu", email = "zhuxudong@ustc.edu.cn" }
]


dependencies = [
  "numpy>=1.26",
  "scipy>=1.10",
  "PyYAML>=5.4",
  "matplotlib>=3.3",
  "spglib>=2.6.0",
  "phonopy>=2.36",
  "pymatgen>=2024.0.0"
]


[project.urls]
Homepage = "https://github.com/xdzhu/zstar"
Repository = "https://github.com/xdzhu/zstar"

[project.scripts]
zstar = "zstar.cli:zstar_cli"

[tool.setuptools.packages.find]
where = ["."]
include = ["zstar"]
