"""Regenerate the matched-mode spectroscopy reference audit."""

from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parent / "source_data"
MODE_FILES = {
    ("CH4", "ir"): ROOT / "molecular" / "ch4" / "ir_modes.csv",
    ("CH4", "raman"): ROOT / "molecular" / "ch4" / "raman_modes.csv",
    ("GaAsNW", "ir"): ROOT / "gaas_nanowire" / "ir" / "ir_modes.csv",
    ("GaAsNW", "raman"): ROOT / "gaas_nanowire" / "raman" / "raman_modes.csv",
    ("MoS2", "ir"): ROOT / "mos2" / "ir" / "ir_modes.csv",
    ("MoS2", "raman"): ROOT / "mos2" / "raman" / "raman_modes.csv",
    ("HfO2", "ir"): ROOT / "hfo2" / "ir" / "ir_modes.csv",
    ("HfO2", "raman"): ROOT / "hfo2" / "raman" / "raman_modes.csv",
}
SCOPES = {
    "CH4": "NIST evaluated gas-phase fundamentals; experiment includes anharmonicity",
    "GaAsNW": "same 24-atom nanowire; independent QE/PBE 1D-DFPT calculation",
    "MoS2": "same monolayer phase; VASP/PBE-D3 versus ABACUS/PBE-D3(BJ)",
    "HfO2": "same tetragonal P42/nmc phase and PBEsol functional; ABACUS/PYATB versus VASP lattice dynamics",
}
FIELDS = (
    "system",
    "channel",
    "mode",
    "irrep",
    "zstar_frequency_cm-1",
    "reference_frequency_cm-1",
    "signed_error_cm-1",
    "absolute_error_cm-1",
    "signed_error_percent",
    "citation_key",
    "doi",
    "comparison_scope",
)


def read_modes(path: Path) -> dict[int, float]:
    with path.open(newline="", encoding="utf-8") as handle:
        return {int(row["mode"]): float(row["frequency_cm-1"]) for row in csv.DictReader(handle)}


def main() -> None:
    mode_tables = {key: read_modes(path) for key, path in MODE_FILES.items()}
    records: list[dict[str, str]] = []
    with (ROOT / "spectroscopy_literature_peaks.csv").open(newline="", encoding="utf-8") as handle:
        for reference in csv.DictReader(handle):
            key = (reference["system"], reference["channel"])
            zstar = mode_tables[key][int(reference["mode"])]
            published = float(reference["frequency_cm-1"])
            error = zstar - published
            records.append(
                {
                    "system": key[0],
                    "channel": key[1],
                    "mode": reference["mode"],
                    "irrep": reference["irrep"],
                    "zstar_frequency_cm-1": f"{zstar:.6f}",
                    "reference_frequency_cm-1": f"{published:.6f}",
                    "signed_error_cm-1": f"{error:.6f}",
                    "absolute_error_cm-1": f"{abs(error):.6f}",
                    "signed_error_percent": f"{100.0 * error / published:.4f}",
                    "citation_key": reference["citation_key"],
                    "doi": reference["doi"],
                    "comparison_scope": SCOPES[key[0]],
                }
            )

    with (ROOT / "spectroscopy_reference_audit.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(records)

    groups: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for record in records:
        groups[(record["system"], record["channel"])].append(record)
    lines = [
        "# Spectroscopy reference audit",
        "",
        "This report is generated by `audit_spectroscopy_references.py`. It compares",
        "matched mode positions only; it does not compare absolute literature and ZStar intensities.",
        "",
        "| System | Channel | N | MAE (cm-1) | Max abs. error (cm-1) | Mean signed error (%) |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for key in MODE_FILES:
        group = groups[key]
        absolute = np.array([float(row["absolute_error_cm-1"]) for row in group])
        percent = np.array([float(row["signed_error_percent"]) for row in group])
        lines.append(
            f"| {key[0]} | {key[1]} | {len(group)} | {absolute.mean():.2f} | "
            f"{absolute.max():.2f} | {percent.mean():+.2f} |"
        )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- CH4 is compared with evaluated experimental fundamentals, so the residual includes anharmonicity absent from the harmonic ZStar calculation.",
            "- The GaAs nanowire uses the same 24-atom structure and provides the cleanest independent code-to-code frequency check.",
            "- MoS2 compares ABACUS/PBE-D3(BJ) with VASP/PBE-D3 for the same monolayer phase; it tests frequencies, mode ordering, and selection rules without assuming code-identical pseudopotentials.",
            "- Tetragonal HfO2 compares the same P42/nmc phase and PBEsol functional. The reference bar heights come from Fan et al., while the frequency audit remains independent of intensity convention.",
            "",
        ]
    )
    (ROOT / "SPECTROSCOPY_AUDIT.md").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
