"""Render the direct benchmark from its measured JSON, not hand-entered values."""

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
folder = ROOT/'docs/research/shared_response'
data = json.loads((folder/'direct_benchmark.json').read_text())
labels = {'sic': '3C-SiC', 'hfo2': 't-HfO2', 'in2se3': 'alpha-In2Se3'}
lines = ['# Direct shared-response validation', '',
         'Generated by `tools/shared_response/write_validation_report.py` from',
         '`direct_benchmark.json`. Retrospective archives are reported separately.', '',
         '## Matched central controls', '',
         'Both ensembles use the same fixed geometry, basis, electronic settings,',
         'and displacement norm. Counts exclude the reference; timings include it.',
         'All reported tensor differences retain the raw-data distinction.', '',
         '| Case | Cartesian / shared displacements | Max raw BEC difference (e) | Max frequency difference (cm^-1) | Relative phonon static difference (%) | Cartesian / shared core-h |',
         '| --- | ---: | ---: | ---: | ---: | ---: |']
for name, case in data['cases'].items():
    a, b, c = case['shared'], case['cartesian'], case['comparison']
    if c['status'] != 'compared':
        lines.append(f'| {labels[name]} | pending | pending | pending | pending | pending |')
        continue
    lines.append(f"| {labels[name]} | {b['displacements']} / {a['displacements']} | {c['max_BEC_difference_raw_e']:.3g} | {c['max_frequency_difference_cm1']:.3g} | {100*c['relative_phonon_static_Frobenius_difference']:.4g} | {b['reserved_core_hours_completed_components']:.3f} / {a['reserved_core_hours_completed_components']:.3f} |")
lines += ['', 'Static response means epsilon_ph for bulk, and Gaussian sheet phonon',
          'polarizability for the monolayer. Molecular or unstable references are not',
          'assigned a stable bulk dielectric constant.', '', '## Independent checks', '']
for name, case in data['cases'].items():
    a = case['shared']
    if a['status'] != 'joint_result_available':
        continue
    lines += [f"- {labels[name]}: force Jacobian versus independent Phonopy reconstruction:",
              f"  {a['independent_phonopy_raw_force_constants_max_difference_eV_A2']:.3g} eV/Angstrom^2;",
              f"  mode-sum versus Hessian static closure: {a['mode_sum_vs_Hessian_static_relative_difference']:.3g} relative."]
lines += ['', 'The raw Jacobian and Phonopy native force-constant array differ by a',
          'combined atom/Cartesian transpose before reciprocity is imposed.',
          'Exact agreement of reconstruction does not remove residual force noise,',
          'finite-step error, or incomplete basis/grid convergence. Raw charge and',
          'force sum rules and reciprocity residuals are retained in every result.', '',
          '## In2Se3 step convergence', '']
case = data['cases']['in2se3']
for key in ('step_comparison', 'matched_half_step_comparison', 'cartesian_step_comparison'):
    result = case.get(key)
    if not result:
        lines.append(f'- {key}: pending.')
    else:
        lines.append(f"- {key}: max raw BEC difference {result['max_BEC_difference_raw_e']:.4g} e; max frequency difference {result['max_frequency_difference_cm1']:.4g} cm^-1; relative static difference {100*result['relative_phonon_static_Frobenius_difference']:.4g}%.")
lines += ['', 'The full step is 0.02 bohr; the half step is 0.01 bohr. Both use actual',
          'serialized STRU vectors. The low optical pair near 18 cm^-1 makes the',
          'static response particularly sensitive to small force-constant changes.', '',
          '## In2Se3 Berry-mesh convergence', '',
          'Halving the displacement did not remove the in-plane BEC discrepancy.',
          'Increasing the Berry integration mesh did. The central Se site gives:', '',
          '| In-plane Berry mesh | Max in-plane shared/control BEC difference (e) |',
          '| --- | ---: |',
          f"| 22 x 22 | {abs(case['shared']['born_raw_e'][3][0][0]-case['cartesian']['born_raw_e'][3][0][0]):.4g} |"]
for item in data.get('in2se3_Berry_mesh_diagnostics', []):
    lines.append(f"| {item['mesh'][0]} x {item['mesh'][1]} | {item['max_in_plane_BEC_difference_e']:.4g} |")
lines += ['', 'These diagnostics use only the in-plane Berry rows. Their out-of-plane',
          'Berry values are not physical slab BECs and are not used: production',
          'normal responses come from the unchanged charge-cube integrations.',
          'The Cartesian symmetry-forbidden transverse response decreases with',
          'mesh refinement. Its leakage into a mixed seed is amplified by the',
          'ratio of normal to in-plane displacement components.', '']
dense = case.get('dense_mesh')
if dense:
    comparison = dense['comparison']
    lines += [f"Full 88 x 88 x 2 refinement: raw BEC max difference **{comparison['max_BEC_difference_raw_e']:.4g} e**;",
              f"projected BEC max difference {comparison['max_BEC_difference_projected_e']:.4g} e;",
              f"frequency max difference {comparison['max_frequency_difference_cm1']:.4g} cm^-1;",
              f"static relative difference {100*comparison['relative_phonon_static_Frobenius_difference']:.4g}%;",
              f"degenerate-group oscillator relative difference {100*comparison['relative_group_oscillator_Frobenius_difference']:.4g}%.", '',
              'All original SCFs, force constants, and reference electronic dielectric',
              'data were reused. Only polarization was recalculated; refined outputs',
              'live in separate trees. Additional measured costs (not hidden in the',
              'baseline timing or called additional SCFs):']
    for scheme in ('shared','cartesian'):
        cost = dense[scheme]['berry_refinement_cost']['additional_reserved_core_hours']
        lines.append(f'- {scheme}: {cost:.3f} core-h for the full polarization refinement, including reused 88-mesh diagnostic stages once.')
    lines += ['', 'The refined comparison satisfies the declared investigation targets.',
              'The approximately 1.1% shared static step sensitivity still limits an',
              'absolute convergence claim for this soft-mode structure. Numerical',
              'equivalence of the two ensembles is not proof of fully converged DFT.', '']
else:
    lines += ['Full refined ensemble comparison remains pending.', '']
lines += ['## Timing scope', '',
          'Hardware verified on cu24/cu25: two Xeon Gold 6248 sockets, 20 physical',
          'cores each, no SMT. The allocation is 40 cores per worker. SiC/In2Se3',
          'used 1 MPI x 40 OMP. The matched HfO2 pair used 1 MPI x 40 OMP ABACUS',
          'and 40 MPI x 1 OMP PYATB. The earlier partial HfO2 1-MPI run and the',
          'contended cu26 attempt are retained remotely and excluded from the ratio.', '',
          'Full-precision polarization diagnostics reused the original SCFs and',
          'only repeated PYATB polarization. Their additional measured costs are',
          'listed below and excluded from the normal one-pass production timing.',
          'The adapter changes output formatting only, not the numerical kernel.', '']
for name, case in data['cases'].items():
    for scheme in ('shared', 'cartesian', 'half_step', 'cartesian_half'):
        result = case.get(scheme, {})
        cost = result.get('output_precision_diagnostic_core_hours', 0)
        if cost:
            lines.append(f"- {labels[name]} {scheme}: {cost:.3f} extra core-h; rounded-text replay check {result.get('precision_rerun_legacy_text_check')}.")
lines += ['', '## Historical separate-workflow context', '',
          'These archived timings are not the matched central-control denominator.',
          'They include the old separate phonon/BEC/IR route, its original step,',
          'postprocessing, and execution profile. Raman and relaxation are excluded.', '',
          '| Case | Archived separate phonon/BEC/IR core-h | New shared core-h |',
          '| --- | ---: | ---: |']
with (ROOT/'examples/backend_examples/calculator_spectroscopy/benchmark_resources.csv').open() as handle:
    for row in csv.DictReader(handle):
        if row['route'] != 'ABACUS+PYATB':
            continue
        name = next(k for k, v in labels.items() if v == row['system'])
        cost = data['cases'][name]['shared'].get('reserved_core_hours_completed_components')
        lines.append(f"| {row['system']} | {float(row['phonon_bec_ir_core_h']):.3f} | {cost:.3f} |")
lines += ['', 'The new matched controls isolate displacement selection. The historical',
          'table gives resource context only; no cross-profile causal speedup is',
          'claimed from it. Raman polarizability derivatives and finite-q supercell',
          'phonons remain separate calculations.', '']
(folder/'DIRECT_VALIDATION.md').write_text('\n'.join(lines), encoding='utf-8')
